sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRCihJV2fcjx9Y8hZLT
    access-key-secret: 3cpdXbLlFfGSLtgMY4sXzOKdGSVS4T
    bucket-name: mjy-djx
  redis:
      host: localhost
      port: 6379
      password: 123456
      database: 10
  wechat:
      appid: wxaf44bdd2846c4451
      secret: c674064c53648c4fdb6c40a273625815
